<?php
use FileCMS\Common\Image\Captcha;
use FileCMS\Common\Data\Storage;
use FileCMS\Common\Generic\Messages;
use FileCMS\Common\Contact\{Email,AntiSpam};
use FileCMS\Common\Security\{Filter,Validation};
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
$message = Messages::getInstance();
$fields = $config['COMPANY_EMAIL']['fields'] ?? [];
if ($_POST) {
    $no_fill = TRUE;
    if (!empty($_POST['no_fill'])) {
        $no_fill = FALSE;
        $msg = $config['COMPANY_EMAIL']['ERROR'] ?? Email::DEFAULT_ERROR;
        error_log(__FILE__);
        error_log(AntiSpam::ERR_NO_FILL);
        error_log($_SERVER['REMOTE_ADDR'] ?? 'Unknown IP Address');
    }
    $body = '';
    $log = $config['CONTACT_LOG'];
    $inputs = $_POST;
    $expected = 0;
    $actual   = 0;
    if (!empty($fields) && $no_fill) {
        // validate form data
        foreach ($fields as $name => $settings) {
            $text = $inputs[$name] ?? '';
            if (!empty($text)) {
                $callbacks = $settings['validator'] ?? [];
                if (!empty($callbacks)) {
                    $expected++;
                    $actual += (int) Validation::runValidators($text, $callbacks);
                }
            }
        }
        if ($expectd !== $actual) {
            $msg = Validation::getMessages();
        } else {
            // filter form data
            foreach ($fields as $name => $settings) {
                $text = &$inputs[$name] ?? '';
                if (!empty($text)) {
                    $callbacks = $settings['filter'] ?? [];
                    if (!empty($callbacks))
                        $text = Filter::runFilters($text, $callbacks);
                }
            }
            // send if CAPTCHA validates
            if (AntiSpam::verifyCaptcha($config)) {
                // send sanitized email data
                $msg = Email::processPost($config, $inputs, $body);
                $message->addMessage($msg);
                // store message in file
                // default is CSV, append mode
                // set STORAGE::storage_fmt = "php|json" in config file if CSV not desired
                $store = new Storage($config);
                $storage->save($inputs);
                // log body + message
                $body .= (!empty($msg)) ? "\n" . strip_tags($msg) . "\n" : '';
                if ($body) file_put_contents($log, $body, FILE_APPEND);
            }
        }
    }
}
// generate CAPTCHA
$hashKey = $config['CAPTCHA']['sess_hash_key'] ?? 'hash';
$token   = bin2hex(random_bytes(4));
$captcha = new Captcha($config['CAPTCHA']);
$images  = $captcha->writeImages($token);
$hash    = password_hash($captcha->phrase, PASSWORD_BCRYPT);
$_SESSION[$hashKey] = $hash;
$msg = $message->getMessages() ?? '';
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Leave a Message</h1>
          <p class="lead mb-5 text-white-50">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non possimus ab labore provident mollitia. Id assumenda voluptate earum corporis facere quibusdam quisquam iste ipsa cumque unde nisi, totam quas ipsam.</p>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-6">
           <?php if (!empty($msg)) : ?>
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg" role="alert">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
            <?php endif; ?>
            <!-- Contacts Form -->
            <form class="contact_form" action="/contact" method="post">
                <div class="row">
                    <?php if (empty($fields)) : ?>
                        <?php include __DIR__ . '/../layout/contact.html'; ?>
                    <?php else : ?>
                        <?php foreach ($fields as $key => $item) : ?>
                            <?php $type = $item['attributes']['type'] ?? 'text'; ?>
                            <?php $name = $item['attributes']['name'] ?? 'unknown'; ?>
                            <?php $attr = $item['attributes'] ?? []; ?>
                            <?php if ($type === 'textarea') : ?>
                                <!-- Textarea -->
                                <div class="col-sm-6 mb-6">
                                    <div class="form-group">
                                        <label class="h6 small d-block text-uppercase">
                                            <?= $item['label'] ?? 'Unknown' ?>
                                            <span class="text-danger">*</span>
                                        </label>

                                        <div class="input-group">
                                            <textarea name="<?= $name ?>" id="<?= $name ?>" <?php foreach ($attr as $x => $y) echo $x . '="' . $y . '" '; ?> >
                                            </textarea>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Textarea -->
                            <?php elseif ($type === 'hidden') : ?>
                                <!-- Hidden -->
                                <input name="<?= $name ?>" id="<?= $name ?>" <?php foreach ($attr as $x => $y) echo $x . '="' . $y . '" '; ?> >
                                <!-- End Text -->
                            <?php else : ?>
                                <!-- Text -->
                                <div class="col-sm-6 mb-6">
                                    <div class="form-group">
                                        <label class="h6 small d-block text-uppercase">
                                            <?= $item['label'] ?? 'Unknown' ?>
                                            <span class="text-danger">*</span>
                                        </label>

                                        <div class="input-group">
                                            <input name="<?= $name ?>" id="<?= $name ?>" <?php foreach ($attr as $x => $y) echo $x . '="' . $y . '" '; ?> />
                                        </div>
                                    </div>
                                </div>
                                <!-- End Text -->
                            <?php endif ; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>

                <div class="">
                    <br />
                    &nbsp;&nbsp;Prove you're human! Enter the characters below:<br />&nbsp;&nbsp;
                    <?php foreach ($images as $fn) : ?><img src="/img/captcha/<?= $fn; ?>" style="width:50px;height:auto;" /><?php endforeach; ?>
                    &nbsp;<input type="text" name="phrase" placeholder="I'm not a robot" /><br /><br />
                    <input type="hidden" id="source" name="source" value="<?= $config['HOST'] . $uri; ?>">
                    <input type="hidden" id="no_fill" name="no_fill" value="" />
                    <input name="submit" type="submit" class="btn btn-primary btn-circled" value="Send Message">
                    <p class="small pt-3">We'll get back to you in 1-2 business days.</p>
                </div>
            </form>
            <!-- End Contacts Form -->
        </div>

        <div class="col-lg-6 col-md-6">
            <!-- START MAP -->
            <div id="map" ></div>
            <!-- END MAP -->
        </div>
    </div>
  </div>
