<?php
use FileCMS\Common\Page\Edit;
use FileCMS\Common\Security\Profile;
use FileCMS\Common\Generic\Messages;
use FileCMS\Common\Transform\TransformInterface;
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// init vars
$contents  = '';
$edit      = new Edit($config);
$message   = Messages::getInstance();
$super_url = $config['SUPER']['super_url'] ?? Edit::DEFAULT_SUPER;
// build dropdown list of existing pages
$pages = $edit->getListOfPages();
$select = '<select name="page_key" class="form-control" placeholder="Choose">' . PHP_EOL;
$select .= '<option>' . Edit::CHOOSE_TOP . '</option>' . PHP_EOL;
foreach (array_keys($pages) as $key)
    $select .= '<option>' . $key . '</option>' . PHP_EOL;
$select .= '</select>' . PHP_EOL;
// get messages
$msg     = $message->getMessages() ?? Messages::CHOOSE;
?>
  <!-- Header -->
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-12">
        <h1 class="display-4 mt-5 mb-2">Choose</h1>
        <p class="lead mb-5 text-white-50">Use this page choose the web page from this website you wish to edit or delete.
        To add a new page, enter a URL and click "Add New Page" button.
        If you wish to import and/or edit a page from another website click <a href="/super/import" style="color:white;">here</a>.
        This menu only allows you to edit pages on <i>this</i> website!</p>
        <?php include ($config['SUPER']['super_menu'] ?? '') ?>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
        <div class="col-lg-12">
          <form class="choose_form" action="<?= $super_url ?>/edit" method="get">
            <h2>Edit Existing Page</h2>
            <div class="form-group">
                <label class="h6 small d-block text-uppercase">
                    Enter URL from this Website (or choose from Page List)
                    <span class="text-danger">*</span>
                </label>
                <div class="input-group">
                    <input class="form-control" name="page_url" id="page_url" size=60 placeholder="http://company.com/page/title" type="text" />
                </div>
            </div>
            <div class="form-group">
                <label class="h6 small d-block text-uppercase">
                    Choose from Page List (or Enter URL)
                    <span class="text-danger">*</span>
                </label>
                <div class="input-group"><?= $select ?></div>
            </div>
            <div class="form-group">
                <input name="choose_edit_page" type="submit" class="btn btn-primary btn-circled" value="Edit Existing Page">
                <input name="choose_new_page" type="submit" class="btn btn-primary btn-circled" value="Add New Page">
                <input name="choose_del_page" type="submit" class="btn btn-primary btn-circled" value="Delete Page">
            </div>
          </form>
        </div>
    </div><!-- row -->

    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-success contact__msg">
                <?= $msg ?>
            </div>
        </div>
    </div>

  </div><!-- container -->
