<?php
use FileCMS\Common\View\Table;
use FileCMS\Common\Stats\Clicks;
use FileCMS\Common\Generic\Messages;
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
$message  = Messages::getInstance();
// grab clicks
$click_fn = $config['CLICK_CSV'] ?? BASE_DIR . '/logs/clicks.csv';
if (!empty($_POST['raw_data'])) {
    header('Content-type: text/csv');
    header('Content-Disposition: attachment; filename="clicks.csv"');
    ob_clean();
    readfile($click_fn);
    exit;
}
// format clicks as HTML table
$css_class = [
    'td' => 't-cell',
    'th' => 't-cell',
];
switch (TRUE) {
    case (!empty($_POST['by_day'])) :
        $clicks  = Clicks::get_by_page_by_day($click_fn);
        $headers = [Clicks::CLICK_HEADERS[0],Clicks::CLICK_HEADERS[1],Clicks::CLICK_HEADERS[6]];
        $html    = Table::render_table($clicks, $headers, [], $css_class);
        break;
    case (!empty($_POST['by_month'])) :
        $callback = function ($row) {
            $val = FALSE;
            if (!empty($row[0]) && !empty($row[1])) {
                $val = $row[0] . '-' . substr($row[1], 0, 7);
            }
            return $val;
        };
        $clicks    = Clicks::raw_get($click_fn, $callback);
        $headers   = [Clicks::CLICK_HEADERS[0],Clicks::CLICK_HEADERS[1],Clicks::CLICK_HEADERS[6]];
        $callbacks = [
            1 => function ($item) {
                     $date = new DateTime($item);
                     return $date->format(Clicks::MONTH_FMT);
                 }
        ];
        $html = Table::render_table($clicks, $headers, $callbacks, $css_class);
        break;
    case (!empty($_POST['by_url'])) :
        $path    = $_POST['path'] ?? '/home';
        $clicks  = Clicks::get_by_path($click_fn, $path);
        $headers = [Clicks::CLICK_HEADERS[0],Clicks::CLICK_HEADERS[1],Clicks::CLICK_HEADERS[6]];
        $callbacks = [
            1 => function ($item) {
                     $date = new DateTime($item);
                     return $date->format(Clicks::MONTH_FMT);
                 }
        ];
        $html    = Table::render_table($clicks, $headers, $callbacks, $css_class);
        break;
    case (!empty($_POST['totals'])) :
    default :
        $clicks  = Clicks::get($click_fn);
        $headers = [Clicks::CLICK_HEADERS[0], Clicks::CLICK_HEADERS[6]];
        $html    = Table::render_table($clicks, $headers, [], $css_class);
        break;
}
if (empty($clicks)) {
    $html = 'No Data';
}
// get messages
$msg = $message->getMessages() ?? 'Enter a URL to import.';
?>
  <style>
  .t-cell {
      border: thin solid gray;
  }
  </style>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Clicks</h1>
          <p class="lead mb-5 text-white-50">Page hits totals by URL, by day and by month</p>
          <?php include ($config['SUPER']['super_menu'] ?? '') ?>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-12">
        <br />
        <form method="post">
        <input type="submit" name="raw_data" value="Download Raw Data" />&nbsp;
        <input type="submit" name="totals" value="Totals" />&nbsp;
        <input type="submit" name="by_day" value="By Day" />&nbsp;
        <input type="submit" name="by_month" value="By Month" />&nbsp;
        <input type="text" name="path" value="" placeholder="/enter/url" size="6" style="display:inline-block;width:33%;"/>
        <input type="submit" name="by_url" value="By URL" />
        </form>
        <br />
        <?php echo (!empty($msg)) ? $msg : '' ?>
        <br />
        <?= $html ?>
        </div>
    </div>
  </div>
