<?php
use FileCMS\Common\Stats\Clicks;
use FileCMS\Common\Generic\Messages;
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
$message  = Messages::getInstance();
// grab clicks
$click_fn = $config['CLICK_CSV'] ?? BASE_DIR . '/logs/clicks.csv';
$clicks   = Clicks::get($click_fn);
if (!empty($_POST['data'])) {
    header('Content-type: text/csv');
    header('Content-Disposition: attachment; filename="clicks.csv"');
    ob_clean();
    readfile($click_fn);
    exit;
}
// format clicks as HTML table
$html = '<table border=1>' . PHP_EOL;
$html .= '<tr><th>URL</th><th>Date</th><th>Hits</th></tr>' . PHP_EOL;
foreach ($clicks as $row)
    $html .= vsprintf('<tr><td>%s</td><td>%s</td><td>%6d</td></tr>' . PHP_EOL, $row);
$html .= '</table>' . PHP_EOL;
// get messages
$msg = $message->getMessages() ?? 'Enter a URL to import.';
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Clicks</h1>
          <p class="lead mb-5 text-white-50">Page hits by URL, excluding the home page.
          The reason why the home page is excluded is because it's the default fallback if a URL is not found.
          Hacking attempts results in the home page being displayed and would artificially inflate hit counts.
          Accordingly, hit counts for the home page are not included.
          <?php include ($config['SUPER']['super_menu'] ?? '') ?>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-12">
        <form method="post"><input type="submit" name="data" value="Download Raw Data" /></form>
        <br />
        <?= $html ?>
        </div>
    </div>
  </div>
