<?php
use FileCMS\Common\Page\Edit;
use FileCMS\Common\Security\Profile;
use FileCMS\Common\Generic\Messages;
// process contact post (if any)
// $OBJ == calling instance (usually from /public/index.php)
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// init vars
$key      = '';
$contents = '';
$edit     = new Edit($config);
$message  = Messages::getInstance();
$edit_width = $config['SUPER']['ckeditor']['width'] ?? 900;
$edit_height = $config['SUPER']['ckeditor']['height'] ?? 500;
$super_url   = $config['SUPER']['super_url'] ?? Edit::DEFAULT_SUPER;
$backup_dir  = $config['SUPER']['backup_dir'] ?? BASE_DIR . '/backups';
// acquire key and page_url
$key      = $_REQUEST['page_key'] ?? '';
$key      = ($key === Edit::CHOOSE_TOP) ? '' : $key;
$page_url = $_REQUEST['page_url'] ?? '';
// go to choose if both indicators are empty
if (empty($key)) {
    if (empty($page_url)) {
        header('Location: /super/choose');
        exit;
    }
    $key = $edit->getKeyFromURL($page_url);
}
// establish filename and backup filename
$fn = $edit->getFilenameFromKey($key);
$backup_fn = (!empty($fn))
           ? $edit->getBackupFn($fn, $backup_dir)
           : '';
// determine action
if (!empty($_POST)) {
    // cancel option
    if (isset($_POST['cancel'])) {
        $message->addMessage(Edit::SUCCESS_CANCEL);
    } elseif (isset($_POST['save']) && $_POST['save'] === 'Delete') {
        if (isset($_POST['page_del']) && $_POST['page_del'] === 'Y') {
            if ($edit->delete($key) === TRUE) {
                $message->addMessage(Edit::SUCCESS_DEL);
            } else {
                $message->addMessage(Edit::ERROR_DEL);
            }
            header('Location: /super/choose');
            exit;
        } else {
            $message->addMessage(Edit::SUCCESS_CANCEL);
        }
    } elseif (isset($_POST['choose'])) {
        header('Location: /super/choose');
        exit;
    } elseif (isset($_POST['restore'])) {
        if ($edit->restore($key, $backup_dir, HTML_DIR)) {
            $message->addMessage(Edit::SUCCESS_RESTORE);
        } else {
            $message->addMessage(Edit::ERROR_RESTORE);
        }
    } elseif (isset($_POST['save'])) {
        // save data
        $contents = $_POST['page_content'] ?? '';
        if ($edit->save($key, $contents, $backup_dir, HTML_DIR, TRUE)) {
            $message->addMessage(Edit::SUCCESS_SAVE);
        } else {
            $message->addMessage(Edit::ERROR_SAVE);
        }
    } else {
        $message->addMessage(Edit::SUCCESS_CANCEL);
    }
}
if (isset($_GET['choose_del_page'])) {
    $action = 'delete';
} else {
    $action = 'edit';
}
$contents = $contents ?: $edit->getContentsFromPage($key, HTML_DIR);
// get messages
$msg = $message->getMessages() ?? Messages::EDIT;
?>
  <!-- Header -->
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-12">
        <h1 class="display-4 mt-5 mb-2"><?= ucfirst($action) ?></h1>
        <p class="lead mb-5 text-white-50">Use this page to edit web pages.</p>
        <?php include $config['SUPER']['super_menu'] ?? '' ?>
       </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <!-- Edit Form -->
            <form class="contact_form" action="<?= $super_url ?>/edit" method="post">

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                URL
                                <span class="text-danger">*</span>
                            </label>

                            <div>
                                <input type="text" id="page_key" name="page_key" size=60 value="<?= $key ?>" />
                                &nbsp;&nbsp;
                                <a target="_blank" href="<?= $key ?>" title="This link only works after you have saved your work" />PREVIEW</a>
                                &nbsp;&nbsp;
                                <?php $label = ($action === 'delete') ? 'Delete' : 'Save'; ?>
                                <input name="save" type="submit" class="btn btn-primary btn-circled" value="<?= $label ?>">
                                <?php if (!empty($backup_fn)) : ?>
                                &nbsp;&nbsp;
                                <input name="restore" type="submit" class="btn btn-primary btn-circled" value="Restore" title="Click here to restore from backup (if any exists)">
                                <?php endif; ?>
                                &nbsp;&nbsp;
                                <input name="choose" type="submit" class="btn btn-primary btn-circled" value="Back" title="Click here to choose another page to work with">
                                &nbsp;&nbsp;
                                <input name="cancel" type="submit" class="btn btn-primary btn-circled" value="Cancel">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Input -->

                <?php if ($action === 'delete') : ?>
                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Confirm Deletion
                                <span class="text-danger">*</span>
                            </label>

                            <div>
                                <input type="radio" id="page_del" name="page_del" value="Y" />&nbsp; Yes
                                <input type="radio" id="page_del" name="page_del" value="N" />&nbsp; No
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Input -->
                <?php endif; ?>

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Page Editor
                                <span class="text-danger">*</span>
                            </label>

                            <div>
                                <textarea id="page_content" type="textarea" name="page_content"><?= $contents ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Input -->

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <div class="input-group">
                                <a target="_blank" href="<?= $key ?>" title="This link only works after you have saved your work" />PREVIEW</a>
                                &nbsp;&nbsp;
                                <?php $label = ($action === 'delete') ? 'Delete' : 'Save'; ?>
                                <input name="save" type="submit" class="btn btn-primary btn-circled" value="<?= $label ?>">
                                <?php if (!empty($backup_fn)) : ?>
                                &nbsp;&nbsp;
                                <input name="restore" type="submit" class="btn btn-primary btn-circled" value="Restore" title="Click here to restore from backup (if any exists)">
                                <?php endif; ?>
                                &nbsp;&nbsp;
                                <input name="choose" type="submit" class="btn btn-primary btn-circled" value="Back" title="Click here to choose another page to work with">
                                &nbsp;&nbsp;
                                <input name="cancel" type="submit" class="btn btn-primary btn-circled" value="Cancel">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Input -->

            </form>
            <!-- End Edit Form -->

           <!-- form message -->
           <?php if (!empty($msg)) : ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <!-- end message -->

        </div>

    </div>
  </div>
    <script src="//cdn.ckeditor.com/4.16.2/full/ckeditor.js"></script>
    <script type="text/javascript">
    CKEDITOR.replace('page_content', {
        startupFocus: true,
        filebrowserImageUploadUrl: '/super/upload',
        filebrowserImageBrowseUrl: '/super/browse',
        filebrowserWindowWidth: '800',
        filebrowserWindowHeight: '500',
        width: '<?= $edit_width ?>',
        height: '<?= $edit_height ?>'
    });
    CKEDITOR.config.allowedContent = true;
    </script>
    <?php /*
        CKEDITOR.config.toolbar = [
        { name: 'document', items: [ 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates' ] },
        { name: 'clipboard', items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord' ] },
        { name: 'editing', items: [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
        '/',
        { name: 'justify', items: [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'] },
        { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', 'Blockquote'] },
        { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'] },
        { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
        '/',
        { name: 'insert', items: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', '-', 'Undo', 'Redo' ] },
        { name: 'source', items: [ 'Source' ] },
        '/',
        { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
        { name: 'colors', items: [ 'TextColor', 'BGColor' ] },
        { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
    ];
    */ ?>
