<?php
use FileCMS\Common\Page\Edit;
use FileCMS\Common\Image\Captcha;
use FileCMS\Common\Security\Profile;
use FileCMS\Common\Generic\Messages;
// process contact post (if any)
// $OBJ == calling instance
$uri = '';
$config = [];
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
$hashKey = $config['CAPTCHA']['sess_hash_key'] ?? 'hash';
$message = Messages::getInstance();
$msg     = $message->getMessages() ?? Messages::LOGIN;
$other   = '';
$super_url  = $config['SUPER']['super_url'] ?? Edit::DEFAULT_SUPER;
$validation = $config['SUPER']['validation'] ?? [];
// not used by default, but you can easily add this in
$allowed_ip = $config['SUPER']['allowed_ip'] ?? [];
$ip         = $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1';
if ($_POST) {
    // capture login params
    $name   = $_POST['name']     ?? 'Default';
    $pwd    = $_POST['password'] ?? 'Default';
    $phrase = $_POST['phrase']   ?? 'Default';
    $other  = $_POST['other']    ?? '';
    // get valid info
    $valid_name  = $config['SUPER']['username'] ?? 'Not Set';
    $valid_pwd   = $config['SUPER']['password'] ?? 'Not Set';
    $valid_other = $_SESSION['other'] ?? 'Not Set';
    $valid_hash  = $_SESSION[$hashKey] ?? 'Not Set';
    // expected results
    $expected = 4;
    // validate login
    $valid = 0;
    $valid += (int) ($name === $valid_name);
    $valid += (int) ($pwd  === $valid_pwd);
    $valid += (int) password_verify($phrase, $valid_hash);
    $valid += (int) ($other === $valid_other);
    if ($valid === $expected) {
        // store selected $_SERVER array settings
        Profile::init($config);
        // redirect to "super" area
        header('Location: /super/choose');
        exit;
    } else {
        $msg = $config['SUPER']['message'] ?? Messages::ERROR_LOGIN;
    }
}
// add "other" authentication factor
$other = array_rand($validation);
$_SESSION['other'] = $validation[$other];
// login attempt control
$max      = $config['SUPER']['attempts'] ?? 3;
$attempts = $_SESSION['attempts'] ?? 0;
$_SESSION['attempts'] = ++$attempts;
if ($attempts > $max) {
    sleep(rand(1,5));
    error_log('Excessive Login Attempts: ' . $ip);
}
// generate CAPTCHA
$token   = bin2hex(random_bytes(4));
$captcha = new Captcha($config['CAPTCHA']);
$images  = $captcha->writeImages($token);
$hash    = password_hash($captcha->phrase, PASSWORD_BCRYPT);
$_SESSION[$hashKey] = $hash;
?>
  <!-- Header -->
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-12">
        <h1 class="display-4 mt-5 mb-2">Login</h1>
        <p class="lead mb-5 text-white-50">Use this page to login to the content editor.</p>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
        <div class="col-lg-6">
            <!-- Contacts Form -->
            <form class="contact_form" action="<?= $super_url ?>/login" method="post">
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Username
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="name" id="name" required="1" placeholder="John Doe" type="text" />
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->

                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Password
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="password" id="password" required="1" placeholder="Password" type="password" />
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->

                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                <?= ucfirst($other) ?>
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="other" id="other" required="1" placeholder="<?= ucfirst($other) ?>" type="text" />
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->

                </div>
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            &nbsp;&nbsp;Prove you're human! Enter the characters below:<br />&nbsp;&nbsp;
                            <?php foreach ($images as $fn) : ?><img src="/img/captcha/<?= $fn; ?>" style="width:50px;height:auto;" /><?php endforeach; ?>
                            &nbsp;<input type="text" name="phrase" placeholder="I'm not a robot" /><br /><br />
                            <input type="hidden" id="source" name="source" value="<?= $config['HOST'] . $uri; ?>" />
                            <br />
                            <input name="submit" type="submit" class="btn btn-primary btn-circled" value="Login" />
                        </div>
                    </div>
                    <!-- End Input -->
                </div>
            </form>
            <!-- End Contacts Form -->

           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
        </div>

        <div class="col-lg-6 col-md-6">
            <!-- START MAP -->
            <div id="map" ></div>
            <!-- END MAP -->
        </div>
    </div>
  </div>
