<?php
use FileCMS\Common\Transform\Transform;
use FileCMS\Common\Page\Edit;
use FileCMS\Common\Security\Profile;
use FileCMS\Common\Generic\Messages;
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// init vars
$message   = Messages::getInstance();
$edit      = new Edit($config);
$pages     = $edit->getListOfPages();
$transform = [];
$bulk      = [];
$super_url = $config['SUPER']['super_url'] ?? Edit::DEFAULT_SUPER;
$backup_dir  = $config['SUPER']['backup_dir'] ?? BASE_DIR . '/backups';
$trans_dir   = $config['TRANSFORM']['transform_dir'] ?? SRC_DIR . '/Transform';
$trans_field = $config['TRANSFORM']['transform_file_field'] ?? 'transform_file';
// check to see if we need to transform anything
if (!empty($_POST['choose_transform'])) {
    $key_list = $_POST['page_key'] ?? [];
    if (empty($key_list)) {
        $message->addMessage(Transform::ERR_NO_PAGES);
    } else {
        $trans_keys = $_POST['choose'] ?? [];
        if (empty($trans_keys)) {
            $message->addMessage(Transform::ERR_NO_TRANS);
        } else {
            $transform = Transform::extract_callbacks_from_post($trans_keys, $_POST);
            // perform transforms on selected pages
            if (empty($transform)) {
                $message->addMessage(Transform::ERR_TRANS_UNABLE);
            } else {
                foreach ($key_list as $key) {
                    // get filename
                    $fn = $pages[$key] ?? '';
                    if (empty($fn) || !file_exists($fn)) {
                        $message->addMessage(Edit::ERROR_FILE);
                    } else {
                        $contents = Transform::transform(file_get_contents($fn), $transform);
                        // save using Tidy (last arg)
                        if ($edit->save($key, $contents, $backup_dir, HTML_DIR, TRUE)) {
                            $bulk[] = $key;
                            $message->addMessage(sprintf(Transform::SUCCESS_TRANS, $key));
                        }
                    }
                }
            }
        }
    }
    $message->addMessage('<pre>' . htmlspecialchars(var_export($transform, TRUE)) . '</pre>');
}
// build dropdown list of existing pages to transform
$select = '<select name="page_key[]" class="form-control" placeholder="Choose" multiple size=12>' . PHP_EOL;
$select .= '<option>' . Edit::CHOOSE_TOP . '</option>' . PHP_EOL;
foreach (array_keys($pages) as $key)
    $select .= '<option>' . $key . '</option>' . PHP_EOL;
$select .= '</select>' . PHP_EOL;
// build list of transforms
$transform_list = (Transform::load_transforms($trans_dir))
                ? Transform::get_callback_list_as_html('b')
                : Transform::NOT_AVAILABLE;
// get messages
$msg = $message->getMessages() ?? 'Select one or more pages to transform.';
if (!empty($bulk))
    foreach ($bulk as $key)
        $msg .= '<br /><a target="_blank" href="/super/edit?page_key=' . $key . '">' . $key . '</a>';
?>
  <!-- Header -->
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-12">
        <h1 class="display-4 mt-5 mb-2">Transform</h1>
        <p class="lead mb-5 text-white-50">Use this page to filter and transform existing web pages.
        Automatically creates a backup of any page before it is transformed.
        Be sure to preview the page before you save it.
        You are also given the option to restore the page, in which case it restores from the backup file created.
        <?php include ($config['SUPER']['super_menu'] ?? '') ?>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <!-- Edit Form -->
            <form class="choose_form" action="<?= $super_url ?>/transform" method="post" enctype="multipart/form-data">

                <div class="row">
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Choose from Page List (or Enter URL)
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group"><?= $select ?></div>
                        </div>
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Upload File with List of Pages to Transform
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group"><input type="file" name="<?= $trans_field ?>" /></div>
                            <p>(or manually enter one or more pages to transform)</p>
                        </div>
                    </div>
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Transform Filters to Apply
                            </label>
                            <p>Expand list of transform filters by adding to the <i>TRANSFORM::transforms</i> configuration array</p>
                            <?= $transform_list ?>
                        </div>
                    </div>
                </div>

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <input name="choose_transform" type="submit" class="btn btn-primary btn-circled" value="Transform">
                        </div>
                    </div>
                </div>
                <!-- End Input -->

            </form>
            <!-- End Edit Form -->
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
        </div>

    </div>
  </div>
